"""Increase phone_number length

Revision ID: c520e87d0672
Revises: 38fceae6fd83
Create Date: 2025-04-27 08:57:31.030959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c520e87d0672'
down_revision = '38fceae6fd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE incident_status ADD VALUE IF NOT EXISTS 'resolved';")
    op.execute("ALTER TYPE incident_status ADD VALUE IF NOT EXISTS 'rejected';")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
